apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: backend-feed
  name: backend-feed
spec:
  replicas: 2
  selector: 
    matchLabels:
      service: backend-feed
  template:
    metadata:
      labels:
        service: backend-feed
    spec:
      containers:
      - image: scheele/udacity-restapi-feed
        name: backend-feed
        volumeMounts:
        - name: aws-directory
          mountPath: $HOME/.aws:/root/.aws
        env:
        - name: POSTGRESS_USERNAME
          value : $POSTGRESS_USERNAME
        - name: POSTGRESS_PASSWORD
          value: $POSTGRESS_PASSWORD 
        - name: POSTGRESS_DB
          value: $POSTGRESS_DB 
        - name: POSTGRESS_HOST
          value: $POSTGRESS_HOST 
        - name: AWS_REGION
          value: $AWS_REGION 
        - name: AWS_PROFILE
          value: $AWS_PROFILE 
        - name: AWS_BUCKET
          value: $AWS_BUCKET
        - name: JWT_SECRET
          value: $JWT_SECRET
        - name: URL
          value: "http://localhost:8100"
        imagePullPolicy: Always          
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
      volumes:
      - name: aws-directory
        emptyDir: {}
      restartPolicy: Always