version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: mowamed/image-filter-reverse-proxy 
  backend_user:
    build:
      context: ../../udacity-c3-restapi-user
    image: mowamed/image-filter-restapi-user
  backend_feed:
    build:
      context: ../../udacity-c3-restapi-feed  
    image: mowamed/image-filter-restapi-feed
  frontend:
    build:
      context: ../../udacity-c3-frontend  
    image: mowamed/image-filter-frontend
